# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '03 Tweeter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 
  use_frameworks!

  inhibit_all_warnings!

  # Pods for 03 Tweeter
  pod 'AFNetworking', '~> 3.0'
  pod ‘AFNetworkActivityLogger’, :git => ‘https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => ‘3_0_0’
  pod 'BDBOAuth1Manager', '~> 2.0'

end

#target '03 TweeterTests' do

#end

#target '03 TweeterUITests' do

#end
